name: CI-CDd
env:
  EB_PACAGE_S3_BACKET_NAME: "maestrto69"
  EB_APLICATION_NAME      : "My-OMV"
  EB_ENVIRONMENT_NAME     : "MyOmv-env"
  AWS_REGION_NAME         : "us-east-2"
  



on:
  push:
    branches:
    - master
    
jobs:
  mi-ci-part:
    runs-on: [ubuntu-18.04]
    steps:
      - name: Git clone my repo
        uses: actions/checkout@v1
        
      - name: Configure 
        run: docker login --username=${{secrets.DOCKER_USERNAME}} --email=Maestrto69@gmail.com
        
      - name: Build and push
        run: |
          docker build -t test-ci-client .
          
          docker tag test-ci-client:latest omegalab/test-ci-client:latest
          docker push omegalab/test-ci-client:latest
