name: CI-CDd
env:
  EB_PACAGE_S3_BACKET_NAME: "maestrto69"
  EB_APLICATION_NAME      : "My-OMV"
  EB_ENVIRONMENT_NAME     : "MyOmv-env"
  AWS_REGION_NAME         : "us-east-2"
  



on:
  push:
    branches:
    - master
    

jobs:
  mi-ci-part:
    runs-on: [ubuntu-18.04]
    
    steps:
      - name: Git clone my repo
        uses: actions/checkout@v1
    
        with:
        
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: build and push
        run: |
          docker build -t app2 .
          docker push omegalab/test-ci-client:latest
          
          
          
          
          
          
          
